"""
setup db.

Revision ID: 1a17979a758a
Revises:
Create Date: 2026-04-15 09:49:10.047947

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a17979a758a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "housing_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("num_rooms", sa.Integer(), nullable=False),
        sa.Column("num_bathrooms", sa.Float(), nullable=False),
        sa.Column("sq_feet", sa.Integer(), nullable=False),
        sa.Column("aesthetic", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("has_garage", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_housing_data_city"), "housing_data", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_housing_data_price"), "housing_data", ["price"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_housing_data_price"), table_name="housing_data")
    op.drop_index(op.f("ix_housing_data_city"), table_name="housing_data")
    op.drop_table("housing_data")
    # ### end Alembic commands ###
